# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LTMAN_GRAPHQL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LTMAN_GRAPHQL
 pod 'Apollo'
 pod 'Kingfisher'
end
